# Site
repository: Ravicted/Ravicted.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Julio Mendiola
title: Software Engineer
email: jmend2994@gmail.com
website: https://ravicted.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: julioisabaddie
github_username:  Ravicted
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: julioisabaddie
linkedin_username: https://www.linkedin.com/in/julio-m-14b858b6/
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-globe
  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: itsme.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Julio and I'm a recent graduate from the University of Texas at Rio Grande Valley. 

  I am most skilled in: <mark>Flutter/Dart</mark> and <mark>UI Design</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: See-Food
        link: https://www.youtube.com/watch?v=-qWgy3pHkb4
        # link_text: Project Website
        #additional_links:
         # - title:  sproogen/modern-resume-theme
          #  icon: fab fa-github
           # url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          A mobile application that uses Flutter framework to allow users to search for recipes. Uses Tensorflow to recognize ingredients based off a users images and search for recipes based on those ingredients. Also uses Spoonacular API to grab recipe information and also filter search results to be more approximate.
        description: | # this will include new lines to allow paragraphs
          Me and my collegue David started this project during Covid-19 lockdown.  We wanted a mobile app with a clean UI to search up recipes using foods we scan with the phones camera, returning recipe results using Spoonacular API.  User can also manually input food choice instead of the camera.
         -![alt text](/images/SF1.png "trees")

        

  #- title: Experience # Title for the section
   # layout: list # Type of content section (list/text)
    #content:
     # - layout: left
      #  title: The Boring Company
       # link: boringcompany.com
        # link_text: boringcompany.com
        #sub_title: Senior Network System Administrator
        #caption: November 2017 - Present
        #quote: >
         # Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        #description: | # this will include new lines to allow paragraphs
         #   Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University of Texas at Rio Grande Valley
        caption: 2018-2021
        sub_title: BS Computer Science
        #quote: >
        description: | # this will include new lines to allow paragraphs
          During my time at UTRGV I learnt most of my key skills such as graphic design, designing applications, designing websites, working as a team.

  - title: Tech Stack
    layout: text
    content: | # this will include new lines to allow paragraphs
      Some of my tech stack includes
      - Flutter
      - Javascript
      - HTML
      - CSS
      - Jira
      - jQuery
    #  - ![alt text](/images/SF1.png "trees")
      - Ruby on Rails

    #Look at this cool image  

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
